version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: stocktw
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6

  backend:
    build: ./backend
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

volumes:
  db-data:
